version: '3'
services:
  gamma_blast:
    build: .
    restart: always
    environment:
      - EMAIL_USER=your_email@gmail.com
      - EMAIL_PASSWORD=your_email_password
      - TWILIO_SID=your_twilio_sid
      - TWILIO_TOKEN=your_twilio_token
      - TWILIO_PHONE_NUMBER=your_twilio_phone_number
      - YOUR_PHONE_NUMBER=your_phone_number
    volumes:
      - .:/usr/src/app

